import "./globals.css";
import { nanumMyeongjo, barlowSemiCondensed, playFairDisplay } from "./font.js";
import Navbar from "@/components/navbar/Navbar";

export const metadata = {
    title: "Xiao Yun",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${nanumMyeongjo.variable} ${barlowSemiCondensed.variable} ${playFairDisplay.variable}`}
            >
                <Navbar />
                {children}
            </body>
        </html>
    );
}
