import "./globals.css";
import { nanumMyeongjo, barlowSemiCondensed } from "./font.js";
import Navbar from "@/components/Navbar";

export const metadata = {
    title: "Xiao Yun",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            {/* <body className={nanumMyeongjo.className}>{children}</body> */}
            <body
                className={`${nanumMyeongjo.variable} ${barlowSemiCondensed.variable}`}
            >
                <Navbar />
                {children}
            </body>
        </html>
    );
}
